import { ArrowLeft, Check, Info, Sparkles } from "lucide-react";
import { FormEvent, useState, type ReactNode } from "react";
import { toast } from "sonner";
import { createProduct, updateProduct, type ProductWithRelations, type CreateProductInput } from "@/services/products";
import type { Category } from "@/services/categories";

interface Props { categories: Category[]; product?: ProductWithRelations; onDone: () => void; onCancel: () => void; }

export default function AdminProductForm({ categories, product, onDone, onCancel }: Props) {
  const isEdit = !!product; const [submitting, setSubmitting] = useState(false); const [errors, setErrors] = useState<Record<string, string>>({});
  const [name, setName] = useState(product?.name ?? ""); const [slug, setSlug] = useState(product?.slug ?? ""); const [categoryId, setCategoryId] = useState(product?.category_id ?? (categories[0]?.id ?? "")); const [rentalPrice, setRentalPrice] = useState(String(product?.rental_price ?? "")); const [description, setDescription] = useState(product?.description ?? ""); const [details, setDetails] = useState(product?.details ?? ""); const [sizing, setSizing] = useState(product?.sizing ?? ""); const [fabric, setFabric] = useState(product?.fabric ?? ""); const [color, setColor] = useState(product?.color ?? ""); const [sizes, setSizes] = useState(product?.sizes?.join(", ") ?? ""); const [rentalNote, setRentalNote] = useState(product?.rental_note ?? ""); const [availability, setAvailability] = useState<"Available" | "Limited" | "Unavailable">(product?.availability ?? "Available"); const [isFeatured, setIsFeatured] = useState(product?.is_featured ?? false); const [isPublic, setIsPublic] = useState(product?.is_public ?? true); const [sortOrder, setSortOrder] = useState(String(product?.sort_order ?? 0));
  const autoSlug = (v: string) => setSlug(v.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""));
  const validate = () => { const e: Record<string, string> = {}; if (!name.trim()) e.name = "Product name is required"; if (!slug.trim() || !/^[a-z0-9-]+$/.test(slug)) e.slug = "Use lowercase letters, numbers and hyphens"; if (!categoryId) e.category = "Choose a category"; if (!rentalPrice || Number(rentalPrice) < 0) e.rentalPrice = "Enter a valid price"; setErrors(e); return !Object.keys(e).length; };
  const handleSubmit = async (event: FormEvent) => { event.preventDefault(); if (!validate()) return; setSubmitting(true); try { const input: CreateProductInput = { category_id: categoryId, name: name.trim(), slug: slug.trim(), rental_price: Number(rentalPrice), availability, is_featured: isFeatured, is_public: isPublic, sort_order: Number(sortOrder) || 0 }; if (description.trim()) input.description = description.trim(); if (details.trim()) input.details = details.trim(); if (sizing.trim()) input.sizing = sizing.trim(); if (fabric.trim()) input.fabric = fabric.trim(); if (color.trim()) input.color = color.trim(); if (sizes.trim()) input.sizes = sizes.split(",").map(s => s.trim()).filter(Boolean); if (rentalNote.trim()) input.rental_note = rentalNote.trim(); if (isEdit && product) { await updateProduct(product.id, input); toast.success("Product updated"); } else { await createProduct(input); toast.success("Product created"); } onDone(); } catch (err: any) { toast.error(err.message || "Failed to save product"); } finally { setSubmitting(false); } };
  const field = (label: string, content: ReactNode, error?: string, hint?: string) => <label className="admin-form-field"><span>{label}</span>{content}{hint && <small>{hint}</small>}{error && <em>{error}</em>}</label>;
  return <div className="admin-editor"><div className="admin-editor-head"><button className="admin-back-link" onClick={onCancel}><ArrowLeft size={15} /> Back to products</button><div><span className="admin-section-kicker">Catalogue editor</span><h2>{isEdit ? "Edit product" : "Add a new product"}</h2><p>{isEdit ? "Refine the details and presentation of this piece." : "Bring a new piece into the MK Studio collection."}</p></div><span className="admin-editor-badge"><Sparkles size={14} /> {isEdit ? "Editing" : "Draft"}</span></div>
    <form onSubmit={handleSubmit} className="admin-form-layout"><div className="admin-form-main"><section className="admin-form-card"><div className="admin-form-card-head"><div><span>01</span><h3>Product identity</h3></div><p>Give this piece a clear, memorable home in the catalogue.</p></div>{field("Product name *", <input value={name} onChange={e => { setName(e.target.value); if (!isEdit) autoSlug(e.target.value); }} placeholder="The Velvet Evening Slip" />, errors.name)}{field("URL slug *", <input value={slug} onChange={e => setSlug(e.target.value)} placeholder="velvet-evening-slip" />, errors.slug, "Used for the product page URL")}{field("Category *", <select value={categoryId} onChange={e => setCategoryId(e.target.value)}><option value="">Select a category</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select>, errors.category)}<div className="admin-form-grid">{field("Rental price (PHP) *", <div className="admin-input-prefix"><span>₱</span><input type="number" min="0" value={rentalPrice} onChange={e => setRentalPrice(e.target.value)} placeholder="1,800" /></div>, errors.rentalPrice)}{field("Sort order", <input type="number" min="0" value={sortOrder} onChange={e => setSortOrder(e.target.value)} placeholder="0" />, undefined, "Lower numbers appear first")}</div></section>
      <section className="admin-form-card"><div className="admin-form-card-head"><div><span>02</span><h3>Story & details</h3></div><p>Help guests understand what makes this piece special.</p></div>{field("Short description", <textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="A softly structured silhouette for evenings that call for a little more…" rows={3} />)}{field("Full details", <textarea value={details} onChange={e => setDetails(e.target.value)} placeholder="Share fit notes, styling suggestions and care details." rows={4} />)}<div className="admin-form-grid">{field("Fabric", <input value={fabric} onChange={e => setFabric(e.target.value)} placeholder="Silk velvet" />)}{field("Colour", <input value={color} onChange={e => setColor(e.target.value)} placeholder="Burgundy" />)}</div>{field("Sizing notes", <input value={sizing} onChange={e => setSizing(e.target.value)} placeholder="Fits UK 6–12; true to size." />)}{field("Available sizes", <input value={sizes} onChange={e => setSizes(e.target.value)} placeholder="UK 6, UK 8, UK 10, UK 12" />, undefined, "Separate sizes with commas")}</section></div>
      <aside className="admin-form-aside"><div className="admin-form-card admin-publish-card"><div className="admin-form-card-head"><div><span>03</span><h3>Publish settings</h3></div></div><label className="admin-toggle-row"><span><strong>Public listing</strong><small>Visible on the storefront</small></span><input type="checkbox" checked={isPublic} onChange={e => setIsPublic(e.target.checked)} /><i /></label><label className="admin-toggle-row"><span><strong>Featured piece</strong><small>Highlight on the homepage</small></span><input type="checkbox" checked={isFeatured} onChange={e => setIsFeatured(e.target.checked)} /><i /></label>{field("Availability", <select value={availability} onChange={e => setAvailability(e.target.value as typeof availability)}><option>Available</option><option>Limited</option><option>Unavailable</option></select>)}{field("Rental note", <input value={rentalNote} onChange={e => setRentalNote(e.target.value)} placeholder="3-day rental · Care included" />)}<div className="admin-form-note"><Info size={15} /><span>Images can be added after saving the product.</span></div></div><div className="admin-form-actions"><button type="submit" className="admin-primary-button" disabled={submitting}><Check size={16} /> {submitting ? "Saving…" : isEdit ? "Save changes" : "Create product"}</button><button type="button" className="admin-secondary-button" onClick={onCancel} disabled={submitting}>Cancel</button></div></aside></form></div>;
}
